
server:
  port: 8762
  servlet:
    session:
      timeout: 1m
spring:
  application:
    name: d1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true